# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4114a5ec5afb055f236f73e0bbf58d5c985d14ecb5a0bdacfb34015dbbc27690ea186bab70072892fa1ccc10133e75f2e5fecd2450096ff7472e787c11c34cd

test:
  secret_key_base: 56cd0b31c969607e764c23bc8f3fab7da6cc328908174b48b95e7954c253a0eac7f14b2b748cee8398cf59f99f5516ae5c2d343e65f263e8d36f52befed3eae3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
